### ISSUE TITLE
linenoise leaks 2 bytes on debugger exit

### ISSUE THREAD

**Issue by nkgt** [nkgt/debugger#1]
Steps to reproduce

1. Build debugger with sanitizers enabled and the simple example
2. Execute `./dbg simple`
3. Use the command `quit` to exit the debugger

The sanitizers will output the following error

```
=================================================================
==42644==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x7fda49a73658 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:439
    #1 0x558c1fa676b5 in linenoise /home/nkgt/source/debugger/build/_deps/linenoise-src/src/linenoise.c:1087

SUMMARY: AddressSanitizer: 2 byte(s) leaked in 1 allocation(s).
```

**Comment by nkgt** [comment]
Forgot to clean linenoise memory before exiting the debugger.
